/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    kotlin("jvm") version "2.0.0"
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    // kotlin
    implementation(kotlin("stdlib"))
    // guice
    implementation("com.google.inject:guice:7.0.0")
    // logging
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.23.1") // Log4j SLF4J binding
    implementation("org.apache.logging.log4j:log4j-core:2.23.1")
    implementation("org.apache.logging.log4j:log4j-api:2.23.1")
    implementation("io.github.oshai:kotlin-logging-jvm:7.0.0") // Kotlin-friendly logging wrapper

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.kohsuke.args4j:args4j-maven-plugin:2.37")

    // Azure Functions Java Library
    implementation("com.microsoft.azure.functions:azure-functions-java-library:3.1.0")

    // Storage, FormRecognizer, and SQL
    implementation("com.azure:azure-storage-blob:12.18.0")
    implementation("com.azure:azure-ai-formrecognizer:4.1.8")
    implementation("mysql:mysql-connector-java:8.0.31")

    // PDF Splitter
    implementation("org.apache.pdfbox:pdfbox:3.0.2")

    // Kotlin
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.0.0")

    // Test
    testImplementation("org.jetbrains.kotlin:kotlin-test:2.0.0")
    testImplementation(libs.junit.jupiter)
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testImplementation("org.assertj:assertj-core:3.26.0")
    testImplementation("org.mockito:mockito-core:5.12.0")
    testImplementation("com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}



application {
    // Define the main class for the application.
    mainClass = "com.goldberg.law.PdfExtractorMain"
    // Get the debug property from the command line or gradle.properties
    val suspend = if (project.findProperty("debug")?.toString()?.toBoolean() == true) "y" else "n"
    applicationDefaultJvmArgs = listOf(
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=$suspend,address=5050"
    )
}

tasks.register<JavaExec>("splitPdf") {
    group = "application"
    description = "splits a PDF"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "com.goldberg.law.PdfSplitterMain"
    args = project.findProperty("args")?.toString()?.split(" ") ?: listOf()
    val suspend = if (project.findProperty("debug")?.toString()?.toBoolean() == true) "y" else "n"
    println("Value of suspend is: $suspend.  Properties: ${project.properties}")
    jvmArgs = listOf(
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5050"
    )
    workingDir = projectDir
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
