/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */
import com.fasterxml.jackson.core.JsonParser
import com.fasterxml.jackson.databind.ObjectMapper
import org.jetbrains.kotlin.utils.ifEmpty
import org.jetbrains.kotlin.utils.keysToMap
import java.nio.file.Files
import java.nio.file.Paths

group = "com.goldberg.law"
version = "1.0.0"
plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    kotlin("jvm") version "2.0.0"
    application
    id("com.microsoft.azure.azurefunctions") version "1.16.1"
}

val suspend = if (project.findProperty("debug")?.toString()?.toBoolean() == true) "y" else "n"

val isProd = project.findProperty("prod")?.toString()?.toBoolean() == true

val env = project.findProperty("env") as String?

fun localSettingsFile(): File = when {
    env != null -> project.file("${env}.local.settings.json")
    else -> project.file("local.settings.json")
}

// TODO: this should be passed in on the command line
azurefunctions {
    subscription = "39fd9868-2043-43d5-80a5-4e2e7145ba11"
    resourceGroup = "DefaultResourceGroup"
    appName = if (isProd) "goldberg-tax-law-prod" else "goldberg-tax-law"
    pricingTier = "Consumption"
    region = "eastus"
    setRuntime(closureOf<com.microsoft.azure.gradle.configuration.GradleRuntimeConfig> {
        os("Windows")
    })
    setAuth(closureOf<com.microsoft.azure.gradle.auth.GradleAuthConfig> {
        type = "azure_cli"
    })
    localDebug = "transport=dt_socket,server=y,suspend=$suspend,address=5005"
    setDeployment(closureOf<com.microsoft.azure.plugin.functions.gradle.configuration.deploy.Deployment> {
        type = "run_from_blob"
    })
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    // kotlin
    implementation(kotlin("stdlib"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    // guice
    implementation("com.google.inject:guice:7.0.0")
    // logging
    implementation("org.slf4j:slf4j-jdk14:2.0.16")
    implementation("io.github.oshai:kotlin-logging-jvm:7.0.0") // Kotlin-friendly logging wrapper

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.kohsuke.args4j:args4j-maven-plugin:2.37")

    // Azure Functions Java Library
    implementation("com.microsoft.azure.functions:azure-functions-java-library:3.1.0")

    // Storage, FormRecognizer, and SQL
    implementation("com.azure:azure-storage-blob:12.18.0")
    implementation("com.azure:azure-ai-documentintelligence:1.0.2")
    implementation("com.azure:azure-identity:1.13.2")
    implementation("com.microsoft.azure.functions:azure-functions-java-library:3.1.0")
    implementation("com.microsoft.azure.functions:azure-functions-java-spi:1.0.0")
    implementation("com.microsoft:durabletask-azure-functions:1.5.0")
    //implementation("com.azure:azure-sdk-bom:1.2.27")
//    implementation("com.azure:azure-storage-blob")
//    implementation("com.azure:azure-ai-formrecognizer")
    // MySQL Database + Migrations
    implementation("org.flywaydb:flyway-core:9.22.3")
    runtimeOnly("org.flywaydb:flyway-mysql:9.22.3")
    implementation("mysql:mysql-connector-java:8.0.33")
    implementation("com.zaxxer:HikariCP:5.0.1")
    implementation("org.xerial:sqlite-jdbc:3.50.3.0")
    implementation("org.jetbrains.exposed:exposed-core:0.61.0")
    implementation("org.jetbrains.exposed:exposed-dao:0.61.0")
    implementation("org.jetbrains.exposed:exposed-jdbc:0.61.0")
    implementation("org.jetbrains.exposed:exposed-java-time:0.61.0")

    // PDF Splitter
    implementation("org.apache.pdfbox:pdfbox:3.0.2")

    // Kotlin
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.0.0")

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.21.0")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.21.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.21.0")

    // csv parsing
    implementation("org.apache.commons:commons-csv:1.14.1")

    // Anthropic SDK (managed-agent integration + skill publishing)
    implementation("com.anthropic:anthropic-java:2.48.0")

    // Test
    testImplementation("org.jetbrains.kotlin:kotlin-test:2.0.0")
    testImplementation("com.h2database:h2:2.4.240")
    testImplementation(libs.junit.jupiter)
    testImplementation("org.junit.jupiter:junit-jupiter:5.14.2")
    testImplementation("org.assertj:assertj-core:3.27.7")
//    testImplementation("org.mockito:mockito-core:5.12.0")
    testImplementation("org.mockito.kotlin:mockito-kotlin:6.2.3")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

// Reads a settings file as a JsonNode; returns null if the file doesn't exist.
fun readSettingsNode(file: File): com.fasterxml.jackson.databind.JsonNode? {
    if (!file.exists()) return null
    return ObjectMapper().apply { enable(JsonParser.Feature.ALLOW_COMMENTS) }.readTree(file)
}

fun nodeToStringMap(node: com.fasterxml.jackson.databind.JsonNode?): Map<String, String> =
    node?.fields()?.asSequence()?.associate { it.key to it.value.asText() } ?: emptyMap()

// Merges common.local.settings.json with {env}.local.settings.json.
// Env-specific values override common ones at every level.
fun mergedSettings(): Map<String, Any> {
    val common = readSettingsNode(project.file("common.local.settings.json"))
    val override = if (env != null) readSettingsNode(localSettingsFile()) else null

    val values = (nodeToStringMap(common?.get("Values")) + nodeToStringMap(override?.get("Values")))
        .ifEmpty { throw IllegalStateException("No Values found in common.local.settings.json!") }

    return mapOf(
        "IsEncrypted" to ((override?.get("IsEncrypted") ?: common?.get("IsEncrypted"))?.asBoolean() ?: false),
        "Values"      to values,
        "Host"        to (nodeToStringMap(common?.get("Host")) + nodeToStringMap(override?.get("Host")))
    )
}

fun setEnvironmentVariablesFromJson(): Map<String, String> {
    @Suppress("UNCHECKED_CAST")
    return (mergedSettings()["Values"] as Map<String, String>)
}

application {
    // Define the main class for the application.
    mainClass = "com.goldberg.law.PdfExtractorMain"
    // Get the debug property from the command line or gradle.properties
    applicationDefaultJvmArgs = listOf(
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=$suspend,address=5050"
    )
    tasks.named<JavaExec>("run") {
        environment(setEnvironmentVariablesFromJson())
    }
}

tasks.register<JavaExec>("splitPdf") {
    group = "application"
    description = "splits a PDF"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "com.goldberg.law.splitpdftool.PdfSplitterMain"

    val properties = mutableListOf<String>()
    
    project.findProperty("filename")?.toString()?.let { filename ->
        properties.addAll(listOf("-if", filename))
    }
    
    project.findProperty("args")?.toString()?.let { argsProperty ->
        properties.addAll(argsProperty.split(" "))
    }
    
    args = properties
    jvmArgs = listOf(
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=$suspend,address=5050"
    )
    workingDir = projectDir
}

// Publishes each agent's skill (managed-agents/<agent>/skill/) to the Anthropic Skills API,
// creating a new version (or the skill itself on first publish).
tasks.register<JavaExec>("updateSkill") {
    group = "application"
    description = "Publishes managed-agents/<agent>/skill to the Anthropic Skills API"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "com.goldberg.law.skilltool.SkillUploaderMainKt"

    val properties = mutableListOf("--agents-root", project.file("managed-agents").absolutePath)
    project.findProperty("agents")?.toString()?.let { properties.addAll(listOf("--agents", it)) }
    if (project.findProperty("dryRun")?.toString()?.toBoolean() == true) properties.add("--dry-run")

    args = properties
    workingDir = projectDir

    doFirst {
        // Inject env vars from local.settings.json (Values block) so ANTHROPIC_API_KEY is available
        // without exporting it. Tolerant of a missing/empty settings file — then we use the shell env.
        runCatching { setEnvironmentVariablesFromJson() }
            .onSuccess { environment(it) }
            .onFailure { println("updateSkill: no local settings env found; using inherited environment") }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.named("azureFunctionsRun") {
    doFirst {
        // Azure Functions Core Tools always reads local.settings.json — write the merged result there.
        val sources = listOfNotNull("common.local.settings.json", env?.let { "$it.local.settings.json" })
        println("Merging settings from: ${sources.joinToString(" + ")}")
        val merged = mergedSettings()
        ObjectMapper().writerWithDefaultPrettyPrinter().writeValue(project.file("local.settings.json"), merged)
        @Suppress("UNCHECKED_CAST")
        println("Written merged local.settings.json (${(merged["Values"] as Map<String, String>).size} Values keys)")
    }
}
